presubmits:
  - name: pull-kubestellar-docs-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Navigate to docs directory and install dependencies
              npm ci
              # Run linting checks
              npm run lint
              # Check for broken links (if script exists)
              if npm run | grep -q "check-links"; then
                npm run check-links
              fi
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi

  - name: pull-kubestellar-docs-build
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Clean previous builds and caches
              rm -rf ~/.npm ~/.cache node_modules .next
              # Install dependencies
              npm ci
              # Build the Next.js documentation site
              npm run build
              # Verify build artifacts exist
              if [ ! -d ".next" ]; then
                echo "Build failed: .next directory not found"
                exit 1
              fi
              echo "✓ Documentation build completed successfully"
          resources:
            requests:
              memory: 3Gi
              cpu: 2
              ephemeral-storage: 6Gi

  - name: pull-kubestellar-docs-test
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Clean previous installs
              rm -rf ~/.npm ~/.cache node_modules
              # Install dependencies
              npm ci
              # Run tests if they exist
              if npm run | grep -q "test"; then
                npm test
              else
                echo "No test script found, skipping tests"
              fi
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi

  - name: pull-kubestellar-docs-markdown-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Install markdownlint-cli globally
              npm install -g markdownlint-cli
              # Lint markdown files in docs directory
              find docs -name "*.md" -exec markdownlint {} \; || true
              # Check for common documentation issues
              echo "Checking for broken internal links..."
              find docs -name "*.md" -exec grep -l "\[\[.*\]\]" {} \; | head -10 || true
              echo "✓ Markdown linting completed"
          resources:
            requests:
              memory: 1Gi
              cpu: 1
              ephemeral-storage: 2Gi

postsubmits:
  - name: post-kubestellar-docs-deploy-main
    branches:
      - ^main$
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Install dependencies and build
              npm ci
              npm run build

              # Export static site if using static export
              if npm run | grep -q "export"; then
                npm run export
                echo "✓ Static site exported"
              fi

              # Here you would typically deploy to your hosting platform
              # For example, deploying to GitHub Pages, Netlify, or Vercel
              echo "✓ Documentation build ready for deployment"
          resources:
            requests:
              memory: 3Gi
              cpu: 2
              ephemeral-storage: 6Gi

  - name: post-kubestellar-docs-build-dev
    branches:
      - ^dev$
    decorate: true
    clone_uri: "https://github.com/kubestellar/docs"
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              # Build development version of docs
              npm ci
              npm run build
              echo "✓ Development documentation build completed"
          resources:
            requests:
              memory: 3Gi
              cpu: 2
              ephemeral-storage: 6Gi
