apiVersion: v1
kind: Namespace
metadata:
  name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestellar-docs
  namespace: docs
  labels:
    app: kubestellar-docs
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kubestellar-docs
  template:
    metadata:
      labels:
        app: kubestellar-docs
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: kubestellar-docs
          image: iad.ocir.io/id4wyucbsggm/kubestellar-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: kubestellar-docs-lb
  namespace: docs
spec:
  type: LoadBalancer
  selector:
    app: kubestellar-docs
  ports:
    - name: http
      port: 80
      targetPort: 3000
