# Dockerfile.rollout-checker
FROM docker.io/alpine/kubectl:1.34.1@sha256:8413f8890d19aa03f63851654f642957e65ba59654b0c9357ddc6ec0b05b63a6

# Install runtime dependencies and OCI CLI
RUN apk add --no-cache python3 py3-pip bash jq curl gettext \
    && pip install --break-system-packages --no-cache-dir oci-cli==3.86.0 \
    && rm -rf /var/cache/apk/*

# (Optional) Print versions only during rebuild, not build
# ENTRYPOINT ["bash", "-c", "kubectl version --client && oci --version && bash"]

WORKDIR /scripts
ENTRYPOINT ["/bin/bash"]
