apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextra-rollout-sa
  namespace: docs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextra-rollout-role
  namespace: docs
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextra-rollout-rolebinding
  namespace: docs
subjects:
  - kind: ServiceAccount
    name: nextra-rollout-sa
    namespace: docs
roleRef:
  kind: Role
  name: nextra-rollout-role
  apiGroup: rbac.authorization.k8s.io
