name: Add Good First Issue Label

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  label-on-good-first-issue:
    if: github.event.comment.body == '/good-first-issue'
    runs-on: ubuntu-latest
    steps:
      - name: Add "good first issue" label
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['good first issue'],
            });
            console.log('Added label: good first issue');
