name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: "20"

jobs:
  # Code Quality and Build Pipeline
  ci:
    name: Code Quality & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --frozen-lockfile

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Check formatting (Prettier)
        run: npm run format:check
        continue-on-error: false

      - name: TypeScript type check
        run: npm run type-check
        continue-on-error: false

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Verify build output
        run: |
          if [ -d ".next" ]; then
            echo "✅ Build successful - .next directory created"
            echo "Build size info:"
            du -sh .next/
            if [ -f ".next/build-manifest.json" ]; then
              echo "✅ Build manifest exists"
            fi
          else
            echo "❌ Build failed - .next directory not found"
            exit 1
          fi

      - name: Run tests (if available)
        run: npm test
        continue-on-error: false

      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            .next/
            public/
            package.json
            next.config.ts
          retention-days: 7

      - name: Upload CI reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports-${{ github.sha }}
          path: |
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
          retention-days: 3
          if-no-files-found: ignore
