name: Markdown Lint

on:
  pull_request:
    branches: [main]
    paths:
      - "README.md"
      - "CONTRIBUTING.md"
      - "docs/**/*.md"
      - "docs/**/*.mdx"

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Validate markdown rules
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
        with:
          globs: |
            README.md
            CONTRIBUTING.md
            docs/**/*.md
            docs/**/*.mdx
