name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    uses: kubestellar/infra/.github/workflows/reusable-stale.yml@a160acca0bdce1ac6c649e006d680d5f6d53024e  # main
    secrets: inherit
